import type { ClusterConfigDto, ClusterSavePayload } from '../../../shared/contracts/cluster'
import { defineFakeRoute } from 'vite-plugin-fake-server/client'

const clusterStore = new Map<string, ClusterConfigDto>()

function defaultClusterConfig(instanceId: string, instanceName: string): ClusterConfigDto {
  return {
    instanceId,
    instanceName,
    instanceStatus: 'stopped',
    networkMode: 'offline',
    clusterName: instanceName,
    clusterDescription: 'Generated by Game Server Hub',
    clusterPassword: '',
    gameMode: 'survival',
    maxPlayers: 6,
    pvp: false,
    pauseWhenEmpty: true,
    voteEnabled: true,
    clusterIntention: 'cooperative',
    tickRate: 15,
    maxSnapshots: 6,
    shardEnabled: false,
    bindIp: '127.0.0.1',
    masterIp: '127.0.0.1',
    masterPort: 10888,
    clusterKey: 'supersecretkey',
    steamGroupOnly: false,
    steamGroupId: '0',
    steamGroupAdmins: false,
    clusterTokenConfigured: false,
    clusterTokenMasked: null,
    panelRoomSaved: false,
    configDirty: false,
    effectiveHints: ['离线模式：不向 Klei 注册，不会出现在游戏浏览列表'],
    warnings: [],
  }
}

export default defineFakeRoute([
  {
    url: '/fake/app/instance/cluster/online-players',
    method: 'get',
    response: ({ query }) => {
      const instanceId = typeof query.instanceId === 'string' ? query.instanceId : ''
      const existing = clusterStore.get(instanceId)
      const running = existing?.instanceStatus === 'running'
      return {
        error: '',
        status: 1,
        data: {
          instanceId,
          running,
          onlinePlayerCount: running ? 2 : null,
          maxPlayers: existing?.maxPlayers ?? 6,
        },
      }
    },
  },
  {
    url: '/fake/app/instance/cluster',
    method: 'get',
    response: ({ query }) => {
      const instanceId = typeof query.instanceId === 'string' ? query.instanceId : ''
      const existing = clusterStore.get(instanceId)
      if (existing) {
        return { error: '', status: 1, data: existing }
      }
      const data = defaultClusterConfig(instanceId, `实例 ${instanceId.slice(0, 8)}`)
      clusterStore.set(instanceId, data)
      return { error: '', status: 1, data }
    },
  },
  {
    url: '/fake/app/instance/cluster',
    method: 'put',
    response: ({ body }) => {
      const payload = body as ClusterSavePayload
      const instanceId = payload.instanceId?.trim() ?? ''
      if (!instanceId) {
        return { error: '实例 ID 不能为空', status: 1, data: {} }
      }
      if (payload.networkMode === 'public' && !payload.clusterToken?.trim()) {
        const existing = clusterStore.get(instanceId)
        if (!existing?.clusterTokenConfigured) {
          return { error: '公网模式必须提供有效的 Klei 集群令牌', status: 1, data: {} }
        }
      }
      const previous = clusterStore.get(instanceId) ?? defaultClusterConfig(instanceId, payload.clusterName)
      const newToken = payload.clusterToken?.trim() ?? ''
      const tokenConfigured = payload.networkMode === 'public'
        ? Boolean(newToken || previous.clusterTokenConfigured)
        : false
      const clusterTokenMasked = newToken
        ? `pds-****${newToken.slice(-4)}`
        : (tokenConfigured ? previous.clusterTokenMasked : null)
      const next: ClusterConfigDto = {
        ...previous,
        networkMode: payload.networkMode,
        clusterName: payload.clusterName,
        clusterDescription: payload.clusterDescription,
        clusterPassword: payload.clusterPassword,
        gameMode: payload.gameMode,
        maxPlayers: payload.maxPlayers,
        pvp: payload.pvp,
        pauseWhenEmpty: payload.pauseWhenEmpty,
        voteEnabled: payload.voteEnabled,
        clusterIntention: payload.clusterIntention,
        tickRate: payload.tickRate,
        maxSnapshots: payload.maxSnapshots,
        shardEnabled: payload.shardEnabled,
        bindIp: payload.bindIp,
        masterIp: payload.masterIp,
        masterPort: payload.masterPort,
        clusterKey: payload.clusterKey,
        steamGroupOnly: payload.steamGroupOnly,
        steamGroupId: payload.steamGroupId,
        steamGroupAdmins: payload.steamGroupAdmins,
        clusterTokenConfigured: tokenConfigured,
        clusterTokenMasked,
        panelRoomSaved: true,
        configDirty: previous.instanceStatus === 'running',
        effectiveHints: previous.instanceStatus === 'running'
          ? ['实例运行中，配置变更需重启实例后生效']
          : payload.shardEnabled
            ? ['洞穴的端口、地图与世界规则请在「世界设置」中调整']
            : [],
        warnings: payload.networkMode === 'public' && !tokenConfigured
          ? ['公网模式但未配置有效的 Klei 集群令牌']
          : [],
      }
      clusterStore.set(instanceId, next)
      return {
        error: '',
        status: 1,
        data: {
          saved: true,
          restarted: Boolean(payload.restart),
        },
      }
    },
  },
])
