packages:
  - '.'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
autoInstallPeers: true
catalog:
  '@clack/prompts': ^1.7.0
  '@faker-js/faker': ^10.5.0
  '@iconify/json': ^2.2.506
  '@iconify/vue': ^5.0.0
  '@spiriit/vite-plugin-svg-spritemap': ^7.0.1
  '@types/nprogress': ^0.2.3
  '@types/path-browserify': ^1.0.3
  '@unocss/core': ^66.7.5
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-legacy': ^8.2.2
  '@vitejs/plugin-vue': ^6.0.8
  '@vitejs/plugin-vue-jsx': ^5.1.6
  '@vue/tsconfig': ^0.9.1
  '@vueuse/components': ^14.2.1
  '@vueuse/core': ^14.3.0
  '@vueuse/integrations': ^14.2.1
  axios: ^1.18.1
  boxen: ^8.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  '@fastify/cors': ^11.3.0
  '@fastify/static': ^10.1.2
  '@types/dockerode': ^3.3.47
  dayjs: ^1.11.21
  defu: ^6.1.7
  dockerode: ^5.0.1
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  echarts: ^6.1.0
  eruda: ^3.4.3
  es-toolkit: ^1.50.0
  fastify: ^5.10.0
  filesize: ^11.0.22
  hotkeys-js: ^4.0.3
  http-server: ^14.1.1
  lucide-vue-next: ^1.0.0
  mitt: ^3.0.1
  npm-run-all2: ^9.0.2
  nprogress: ^0.2.0
  path-browserify: ^1.0.1
  path-to-regexp: ^8.4.2
  picocolors: ^1.1.1
  pinia: ^4.0.2
  pinia-plugin-persistedstate: ^4.7.1
  pinyin-pro: ^3.28.2
  postcss: ^8.5.23
  postcss-nested: ^7.0.2
  reka-ui: ^2.10.1
  sass-embedded: ^1.100.0
  scule: ^1.3.0
  svgo: ^4.0.2
  tailwind-merge: ^3.5.0
  tsx: ^4.23.1
  type-fest: ^5.8.0
  ua-parser-js: ^2.0.10
  unbuild: ^3.6.1
  unocss: ^66.7.5
  unocss-preset-animations: ^1.3.0
  unplugin-auto-import: ^21.0.0
  unplugin-turbo-console: ^2.3.3
  unplugin-vue-components: ^32.1.0
  vconsole: ^3.15.1
  vee-validate: ^4.15.1
  vite: ^8.1.5
  vite-plugin-app-loading: ^0.6.1
  vite-plugin-archiver: ^0.4.1
  vite-plugin-banner: ^0.8.1
  vite-plugin-compression2: ^2.5.3
  vite-plugin-env-parse: ^1.0.15
  vite-plugin-fake-server: ^2.2.3
  vite-plugin-vue-devtools: ^8.2.1
  vue: ^3.5.40
  vue-input-otp: ^0.3.2
  vue-router: ^5.2.0
  vue-sonner: ^2.0.9
  vue-tsc: ^3.3.8
  zod: ^4.3.6
catalogs:
  naive-ui:
    naive-ui: ^2.44.1
engineStrict: true
shamefullyHoist: true
shellEmulator: true
