packages:
  - '.'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
autoInstallPeers: true
catalog:
  '@clack/prompts': ^1.2.0
  '@faker-js/faker': ^10.4.0
  '@iconify/json': ^2.2.462
  '@iconify/vue': ^5.0.0
  '@spiriit/vite-plugin-svg-spritemap': ^7.0.0
  '@types/nprogress': ^0.2.3
  '@types/path-browserify': ^1.0.3
  '@unocss/core': ^66.6.8
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-legacy': ^8.0.1
  '@vitejs/plugin-vue': ^6.0.6
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vue/tsconfig': ^0.9.1
  '@vueuse/components': ^14.2.1
  '@vueuse/core': ^14.2.1
  '@vueuse/integrations': ^14.2.1
  axios: ^1.15.0
  boxen: ^8.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  '@fastify/cors': ^10.0.1
  '@fastify/static': ^8.2.0
  '@types/dockerode': ^3.3.47
  dayjs: ^1.11.20
  defu: ^6.1.7
  dockerode: ^4.0.9
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  echarts: ^6.0.0
  eruda: ^3.4.3
  es-toolkit: ^1.45.1
  fastify: ^5.8.5
  filesize: ^11.0.15
  hotkeys-js: ^4.0.3
  http-server: ^14.1.1
  lucide-vue-next: ^1.0.0
  mitt: ^3.0.1
  npm-run-all2: ^8.0.4
  nprogress: ^0.2.0
  path-browserify: ^1.0.1
  path-to-regexp: ^8.4.2
  picocolors: ^1.1.1
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  pinyin-pro: ^3.28.1
  postcss: ^8.5.10
  postcss-nested: ^7.0.2
  reka-ui: ^2.9.6
  sass-embedded: ^1.99.0
  scule: ^1.3.0
  svgo: ^4.0.1
  tailwind-merge: ^3.5.0
  tsx: ^4.21.0
  type-fest: ^5.5.0
  ua-parser-js: ^2.0.9
  unbuild: ^3.6.1
  unocss: ^66.6.8
  unocss-preset-animations: ^1.3.0
  unplugin-auto-import: ^21.0.0
  unplugin-turbo-console: ^2.3.0
  unplugin-vue-components: ^32.0.0
  vconsole: ^3.15.1
  vee-validate: ^4.15.1
  vite: ^8.0.8
  vite-plugin-app-loading: ^0.5.4
  vite-plugin-archiver: ^0.3.2
  vite-plugin-banner: ^0.8.1
  vite-plugin-compression2: ^2.5.3
  vite-plugin-env-parse: ^1.0.15
  vite-plugin-fake-server: ^2.2.3
  vite-plugin-vue-devtools: ^8.1.1
  vue: ^3.5.32
  vue-input-otp: ^0.3.2
  vue-router: ^5.0.4
  vue-sonner: ^2.0.9
  vue-tsc: ^3.2.6
  zod: ^4.3.6
catalogs:
  naive-ui:
    naive-ui: ^2.44.1
patchedDependencies:
  '@vitejs/plugin-vue@6.0.7': patches/@vitejs__plugin-vue@6.0.7.patch
engineStrict: true
shamefullyHoist: true
shellEmulator: true
