import fs from 'node:fs'
import path from 'node:path'
import {
  DST_CLUSTER_NAME,
  DST_CONF_DIR,
  DST_DEFAULT_GAME_PORT,
  DST_STORAGE_DIR,
} from './constants'

export interface DstServerBinary {
  binDir: string
  executable: string
}

export interface EnsureDstClusterInput {
  instanceName?: string
  gamePort?: number | null
}

function writeFileIfMissing(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    return
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf8')
}

export function findDstServerBinary(installPath: string): DstServerBinary | undefined {
  const candidates = [
    { binDir: 'bin64', executable: 'dontstarve_dedicated_server_x64' },
    { binDir: 'bin64', executable: 'dontstarve_dedicated_server_nullrenderer_x64' },
    { binDir: 'bin', executable: 'dontstarve_dedicated_server_nullrenderer' },
  ]
  for (const candidate of candidates) {
    const executablePath = path.join(installPath, candidate.binDir, candidate.executable)
    if (fs.existsSync(executablePath)) {
      return candidate
    }
  }
}

function ensureDstSteamAppId(installPath: string, binary: DstServerBinary) {
  const appIdContent = '322330\n'
  writeFileIfMissing(path.join(installPath, binary.binDir, 'steam_appid.txt'), appIdContent)
  writeFileIfMissing(path.join(installPath, 'steam_appid.txt'), appIdContent)
}

function buildDstClusterIni(clusterName: string) {
  const safeClusterName = clusterName.replace(/[\r\n"]/g, ' ').trim() || 'Game Server Hub'
  return [
    '[NETWORK]',
    `cluster_name = ${safeClusterName}`,
    'cluster_description = Generated by Game Server Hub',
    'cluster_password =',
    'offline_cluster = true',
    'lan_only_cluster = true',
    'whitelist_slots = 0',
    'cluster_intention = cooperative',
    'autosaver_enabled = true',
    '',
    '[GAMEPLAY]',
    'game_mode = survival',
    'max_players = 6',
    'pvp = false',
    'pause_when_empty = true',
    '',
    '[MISC]',
    'console_enabled = true',
    '',
    '[SHARD]',
    'shard_enabled = false',
    '',
  ].join('\n')
}

function buildDstMasterServerIni(gamePort: number) {
  return [
    '[SHARD]',
    'is_master = true',
    '',
    '[NETWORK]',
    `server_port = ${gamePort}`,
    '',
    '[STEAM]',
    'master_server_port = 12346',
    'authentication_port = 8766',
    '',
    '[ACCOUNT]',
    'encode_user_path = true',
    '',
  ].join('\n')
}

function buildDstWorldgenOverride() {
  return [
    'return {',
    '  override_enabled = true,',
    '  preset = "SURVIVAL_TOGETHER",',
    '  overrides = {},',
    '}',
    '',
  ].join('\n')
}

export function ensureDstClusterConfig(installPath: string, input: EnsureDstClusterInput) {
  const storageRoot = path.join(installPath, DST_STORAGE_DIR)
  const clusterRoot = path.join(storageRoot, DST_CONF_DIR, DST_CLUSTER_NAME)
  const masterRoot = path.join(clusterRoot, 'Master')
  const gamePort = input.gamePort ?? DST_DEFAULT_GAME_PORT
  writeFileIfMissing(path.join(clusterRoot, 'cluster.ini'), buildDstClusterIni(input.instanceName ?? 'Game Server Hub'))
  writeFileIfMissing(path.join(masterRoot, 'server.ini'), buildDstMasterServerIni(gamePort))
  writeFileIfMissing(path.join(masterRoot, 'worldgenoverride.lua'), buildDstWorldgenOverride())
  return storageRoot
}

export function ensureDstLayout(installPath: string, input: EnsureDstClusterInput): {
  ok: boolean
  message?: string
} {
  const binary = findDstServerBinary(installPath)
  if (!binary) {
    return {
      ok: false,
      message: '未在安装目录找到饥荒联机服务端可执行文件（bin64/bin），请确认 SteamCMD 安装已完成',
    }
  }
  ensureDstSteamAppId(installPath, binary)
  ensureDstClusterConfig(installPath, input)
  return { ok: true }
}

export function buildDstLaunchArgs(storageRoot: string): string[] {
  return [
    '-persistent_storage_root',
    storageRoot,
    '-conf_dir',
    DST_CONF_DIR,
    '-cluster',
    DST_CLUSTER_NAME,
    '-shard',
    'Master',
    '-console',
  ]
}
