import type { ClusterConfigDto, ClusterNetworkMode } from '@/api/modules/cluster'
import type { InstanceItem } from '@/api/modules/instance'
import type { ShardListDto } from '@/api/modules/shard'

import { GAME_CODES } from '@/constants/games'

/** DST 专用服 Steam AppID（与 {@link GAME_CODES.DST} 一致） */
export const DST_GAME_CODE = GAME_CODES.DST

/** 安装时写入 cluster.ini 的默认说明，用于判断是否进过房间设置 */
export const INSTALL_DEFAULT_CLUSTER_DESCRIPTION = 'Generated by Game Server Hub'

const SKIP_GUIDE_STORAGE_PREFIX = 'gsh-skip-start-guide:'

export interface InstanceStartGuideContext {
  instanceId: string
  instanceName: string
  networkMode: ClusterNetworkMode
  clusterTokenConfigured: boolean
  shardEnabled: boolean
  /** 房间说明仍为安装默认文案，视为未在面板保存过房间 */
  roomStillInstallDefault: boolean
}

export function getStartGuideSkipStorageKey(instanceId: string) {
  return `${SKIP_GUIDE_STORAGE_PREFIX}${instanceId}`
}

export function isStartGuideSkipped(instanceId: string) {
  return sessionStorage.getItem(getStartGuideSkipStorageKey(instanceId)) === '1'
}

export function setStartGuideSkipped(instanceId: string) {
  sessionStorage.setItem(getStartGuideSkipStorageKey(instanceId), '1')
}

export function shouldOfferStartGuide(
  row: Pick<InstanceItem, 'gameCode' | 'status' | 'id'>,
  masterWorldGenerated: boolean | undefined,
): boolean {
  if (row.gameCode !== DST_GAME_CODE) {
    return false
  }
  if (row.status !== 'stopped' && row.status !== 'error') {
    return false
  }
  if (masterWorldGenerated) {
    return false
  }
  if (isStartGuideSkipped(row.id)) {
    return false
  }
  return true
}

export function buildInstanceStartGuideContext(
  row: Pick<InstanceItem, 'id' | 'name'>,
  cluster: ClusterConfigDto,
  shardList: ShardListDto,
): InstanceStartGuideContext {
  return {
    instanceId: row.id,
    instanceName: row.name,
    networkMode: cluster.networkMode,
    clusterTokenConfigured: cluster.clusterTokenConfigured,
    shardEnabled: shardList.clusterShardEnabled,
    roomStillInstallDefault: cluster.clusterDescription === INSTALL_DEFAULT_CLUSTER_DESCRIPTION,
  }
}

/** 公网模式但未配置 Klei 令牌：不允许「默认启动」 */
export function blocksDefaultStart(ctx: InstanceStartGuideContext) {
  return ctx.networkMode === 'public' && !ctx.clusterTokenConfigured
}

export function buildStartGuideTitle() {
  return '准备启动服务器'
}

export function buildStartGuideParagraphs(ctx: InstanceStartGuideContext): string[] {
  if (blocksDefaultStart(ctx)) {
    return [
      `实例「${ctx.instanceName}」需要在房间设置里填写 Klei 房间令牌，其他玩家才能从联机列表找到并进入。`,
      '请先到「房间设置」改为合适的联网方式，或补全令牌后再启动。',
    ]
  }

  const lines: string[] = []

  if (ctx.roomStillInstallDefault) {
    lines.push(
      `实例「${ctx.instanceName}」还没在面板里设置过「房间」和「地上世界」的玩法。`,
      '现在也可以直接启动：会使用离线房间和默认地图设置；启动后游戏会自动生成第一张地图。',
    )
  }
  else {
    lines.push(
      `实例「${ctx.instanceName}」已保存过房间设置，但地上世界尚未生成。`,
      '现在启动将按当前房间与世界设置生成地图；若还想改地图大小、群落等细节，请先在「世界设置」里保存后再启动。',
    )
  }

  lines.push('若希望自定义房间名称、密码、是否包含洞穴，可先配置房间；地图生成后，部分世界生成选项将无法再改。')

  if (ctx.shardEnabled) {
    lines.push('已开启洞穴时，洞穴地图会在洞穴服务器首次启动时同样自动生成。')
  }

  return lines
}
