import type { ClusterConfigDto, ClusterNetworkMode } from '@/api/modules/cluster'
import type { InstanceItem } from '@/api/modules/instance'
import type { ShardListDto } from '@/api/modules/shard'

import { GAME_CODES } from '@/constants/games'

/** DST 专用服 Steam AppID（与 {@link GAME_CODES.DST} 一致） */
export const DST_GAME_CODE = GAME_CODES.DST

/** 安装时写入 cluster.ini 的默认说明，用于判断是否进过房间设置 */
export const INSTALL_DEFAULT_CLUSTER_DESCRIPTION = 'Generated by Game Server Hub'

/** 安装时主世界默认 worldgen 预设（与 server buildDstMasterWorldgenContent 一致） */
export const INSTALL_DEFAULT_MASTER_WORLDGEN_PRESET = 'SURVIVAL_TOGETHER'

const SKIP_GUIDE_STORAGE_PREFIX = 'gsh-skip-start-guide:'

export interface InstanceStartGuideContext {
  instanceId: string
  instanceName: string
  networkMode: ClusterNetworkMode
  clusterTokenConfigured: boolean
  shardEnabled: boolean
  roomCustomized: boolean
  worldCustomized: boolean
}

export function getStartGuideSkipStorageKey(instanceId: string) {
  return `${SKIP_GUIDE_STORAGE_PREFIX}${instanceId}`
}

/** 跳过引导跨会话记忆（localStorage）：文案承诺的是「下次启动」，会话级存储关掉浏览器就失效 */
export function isStartGuideSkipped(instanceId: string) {
  const key = getStartGuideSkipStorageKey(instanceId)
  if (localStorage.getItem(key) === '1') {
    return true
  }
  // 旧版本写在 sessionStorage 里，读到即迁移到 localStorage
  if (sessionStorage.getItem(key) === '1') {
    localStorage.setItem(key, '1')
    sessionStorage.removeItem(key)
    return true
  }
  return false
}

export function setStartGuideSkipped(instanceId: string) {
  const key = getStartGuideSkipStorageKey(instanceId)
  localStorage.setItem(key, '1')
  sessionStorage.removeItem(key)
}

export function shouldOfferStartGuide(
  row: Pick<InstanceItem, 'gameCode' | 'status' | 'id'>,
  masterWorldGenerated: boolean | undefined,
): boolean {
  if (row.gameCode !== DST_GAME_CODE) {
    return false
  }
  if (row.status !== 'stopped' && row.status !== 'error') {
    return false
  }
  if (masterWorldGenerated) {
    return false
  }
  if (isStartGuideSkipped(row.id)) {
    return false
  }
  return true
}

export function isRoomSettingsCustomized(cluster: ClusterConfigDto): boolean {
  if (cluster.panelRoomSaved) {
    return true
  }
  if (cluster.clusterDescription !== INSTALL_DEFAULT_CLUSTER_DESCRIPTION) {
    return true
  }
  if (cluster.networkMode !== 'offline') {
    return true
  }
  if (cluster.shardEnabled) {
    return true
  }
  if (cluster.clusterName.trim() !== cluster.instanceName.trim()) {
    return true
  }
  return false
}

export function isWorldSettingsCustomized(shardList: ShardListDto): boolean {
  const master = shardList.shards.find(s => s.id === 'master')
  if (!master) {
    return false
  }
  if (master.panelSaved) {
    return true
  }
  const overrides = master.overrides
  if (overrides && Object.keys(overrides).length > 0) {
    return true
  }
  if (master.worldgenPreset && master.worldgenPreset !== INSTALL_DEFAULT_MASTER_WORLDGEN_PRESET) {
    return true
  }
  return false
}

export function buildInstanceStartGuideContext(
  row: Pick<InstanceItem, 'id' | 'name'>,
  cluster: ClusterConfigDto,
  shardList: ShardListDto,
): InstanceStartGuideContext {
  return {
    instanceId: row.id,
    instanceName: row.name,
    networkMode: cluster.networkMode,
    clusterTokenConfigured: cluster.clusterTokenConfigured,
    shardEnabled: shardList.clusterShardEnabled,
    roomCustomized: isRoomSettingsCustomized(cluster),
    worldCustomized: isWorldSettingsCustomized(shardList),
  }
}

/** 公网模式但未配置 Klei 令牌：不允许「默认启动」 */
export function blocksDefaultStart(ctx: InstanceStartGuideContext) {
  return ctx.networkMode === 'public' && !ctx.clusterTokenConfigured
}

export function buildStartGuideTitle() {
  return '准备启动服务器'
}

export function buildStartGuidePositiveText(ctx: InstanceStartGuideContext): string {
  if (blocksDefaultStart(ctx)) {
    return '去配置房间'
  }
  if (ctx.roomCustomized || ctx.worldCustomized) {
    return '按当前配置启动'
  }
  return '用默认配置启动'
}

export function buildStartGuideParagraphs(ctx: InstanceStartGuideContext): string[] {
  if (blocksDefaultStart(ctx)) {
    return [
      `实例「${ctx.instanceName}」需要在房间设置里填写 Klei 房间令牌，其他玩家才能从联机列表找到并进入。`,
      '请先到「房间设置」改为合适的联网方式，或补全令牌后再启动。',
    ]
  }

  const lines: string[] = []

  if (ctx.roomCustomized && ctx.worldCustomized) {
    lines.push(
      `实例「${ctx.instanceName}」已保存房间与地上世界设置但地图尚未生成，现在启动将按当前配置生成地图。`,
    )
  }
  else if (!ctx.roomCustomized && ctx.worldCustomized) {
    lines.push(
      `实例「${ctx.instanceName}」已在「世界设置」中保存过地上世界玩法，房间仍为默认离线配置。`,
      '现在启动将按当前世界设置生成地图；如需改房间名称、联网方式或洞穴，请先到「房间设置」保存后再启动。',
    )
  }
  else if (ctx.roomCustomized && !ctx.worldCustomized) {
    lines.push(
      `实例「${ctx.instanceName}」已保存过房间设置，但地上世界尚未在面板中定制。`,
      '现在启动将按当前房间与默认地图设置生成地图；若还想改地图大小、群落等细节，请先在「世界设置」里保存后再启动。',
    )
  }
  else {
    lines.push(
      `实例「${ctx.instanceName}」还没在面板里设置过「房间」和「地上世界」的玩法。`,
      '现在也可以直接启动：会使用离线房间和默认地图设置；启动后游戏会自动生成第一张地图。',
    )
  }

  if (!ctx.roomCustomized || !ctx.worldCustomized) {
    lines.push('若希望自定义房间名称、密码、是否包含洞穴，可先配置房间；地图生成后，部分世界生成选项将无法再改。')
  }

  if (ctx.shardEnabled) {
    lines.push('已开启洞穴时，洞穴地图会在洞穴服务器首次启动时同样自动生成。')
  }

  return lines
}
